# Configure admin and day-to-day server users
# Credit to chesterbr at https://github.com/chesterbr/chester-ansible-configs/blob/1027ab684d353ee1208c8bed86321c54195ff5bf/roles/chesterbr.user_setup/tasks/main.yml
---

- name: Create admin user
  become: yes
  ansible.builtin.user:
    name: "{{ admin_user }}"
    shell: /bin/bash

- name: Ensure admin user can log in with their key
  become: yes
  ansible.posix.authorized_key:
    user: "{{ admin_user }}"
    key: "{{ admin_user_ssh_public_key }}"
    state: present
    path: "/home/{{ admin_user }}/.ssh/authorized_keys"

- name: Ensure admin user is a passwordless sudoer
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ admin_user }}"
    line: "{{ admin_user }} ALL=(ALL) NOPASSWD: ALL"
    create: yes
    state: present
    validate: "visudo -cf %s"

- name: Create server user
  become: yes
  ansible.builtin.user:
    name: "{{ server_user }}"
    system: yes