# Server config
timestamped_for_f1_root_dir: "/srv/timestamped-for-f1" # Absolute path to directory for the app
timestamped_for_f1_docker_compose_path: "{{ timestamped_for_f1_root_dir }}/compose.yml"
timestamped_for_f1_dashboard_config_path: "{{ timestamped_for_f1_root_dir }}/dashboard/.env"
timestamped_for_f1_cache_config_path: "{{ timestamped_for_f1_root_dir }}/services/cache/config/redis.conf"
timestamped_for_f1_web_server_config_path: "{{ timestamped_for_f1_root_dir }}/services/web-server/config/Caddyfile"
