services:
  
  openf1-live-mq:
    build:
      context: ./services/openf1-live-mq
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 5672
      - 15672

  openf1-db:
    build:
      context: ./services/openf1-db
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 27017
    volumes:
      - ./data/openf1-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${OPENF1_DB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${OPENF1_DB_ROOT_PASSWORD}"

  openf1:
    image: ghcr.io/jeffreyjpz/timestamped-for-f1-openf1:latest
    ports:
      - 8000:8000
    depends_on:
      - openf1-db
    environment:
      MONGO_CONNECTION_STRING: "mongodb://${OPENF1_DB_ROOT_USERNAME}:${OPENF1_DB_ROOT_PASSWORD}@openf1-db:${OPENF1_DB_PORT}"
      OPENF1_DB_NAME: "${OPENF1_DB_NAME}"

  historical-api:
    build:
      context: ./historical/api
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - historical-db
    environment:
      SQLALCHEMY_URL: "postgresql://${HISTORICAL_DB_ROOT_USERNAME}:${HISTORICAL_DB_ROOT_PASSWORD}@historical-db:${HISTORICAL_DB_PORT}/${HISTORICAL_DB_NAME}"

  historical-processing:
    build:
      context: ./historical/processing
      dockerfile: Dockerfile
    depends_on:
      - openf1
      - openf1-db
      - historical-db
    environment:
      OPENF1_ADDRESS: "openf1:8000"
      SQLALCHEMY_URL: "postgresql://${HISTORICAL_DB_ROOT_USERNAME}:${HISTORICAL_DB_ROOT_PASSWORD}@historical-db:${HISTORICAL_DB_PORT}/${HISTORICAL_DB_NAME}"

  historical-db:
    image: postgres:17.5
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - ./data/historical-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${HISTORICAL_DB_ROOT_USERNAME}"
      POSTGRES_PASSWORD: "${HISTORICAL_DB_ROOT_PASSWORD}"
      POSTGRES_DB: "${HISTORICAL_DB_NAME}"
