# Improve server security from defaults
# Credit to chesterbr https://github.com/chesterbr/chester-ansible-configs/blob/1027ab684d353ee1208c8bed86321c54195ff5bf/roles/chesterbr.security/tasks/main.yml
---

- name: Configure ufw (firewall) to allow specific ports
  become: yes
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 22
    - 80
    - 443

- name: Enable ufw and load it on startup; reject any connections not on rules
  become: yes
  community.general.ufw:
    state: enabled
    policy: reject

- name: Disable password and root login for SSH
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Ensure fail2ban is running and enabled on boot
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true