# Improve server security from defaults
# Credit to chesterbr https://github.com/chesterbr/chester-ansible-configs/blob/1027ab684d353ee1208c8bed86321c54195ff5bf/roles/chesterbr.security/tasks/main.yml
---

- name: Install ufw (firewall)
  become: yes
  ansible.builtin.apt:
    name: ufw
    state: latest
    update_cache: yes

- name: Configure ufw to allow specific ports
  become: yes
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 22
    - 80
    - 443

- name: Enable ufw and load it on startup; reject any connections not on rules
  become: yes
  community.general.ufw:
    state: enabled
    policy: reject

- name: Disable password and root login for SSH
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
    state: present
  loop:
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }

- name: Install fail2ban
  become: yes
  ansible.builtin.apt:
    name: fail2ban
    state: latest
    update_cache: yes

- name: Copy fail2ban config
  become: yes
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: "{{ root_user }}"
    group: "{{ root_user }}"
    mode: "0644"

- name: Ensure fail2ban is running and enabled on boot
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes