# Credit to https://github.com/vercel/next.js/blob/f9f3afc66418f3cc6b206ee50b632f9dd4128dd5/examples/with-docker/Dockerfile
# syntax=docker.io/docker/dockerfile:1

FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi


# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED=1

RUN \
  if [ -f yarn.lock ]; then yarn run build; \
  elif [ -f package-lock.json ]; then npm run build; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

# Uncomment the following line in case you want to disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

# Unfortunately Next.js doesn't work well with runtime environment variables so we have to pass them in at build time
# This is fine as they are not sensitive
ARG TIMESTAMPED_FOR_F1_DASHBOARD_NODE_ENV
ARG TIMESTAMPED_FOR_F1_DASHBOARD_HOST
ARG TIMESTAMPED_FOR_F1_DASHBOARD_PORT
ARG TIMESTAMPED_FOR_F1_DASHBOARD_WEB_API_BASE_URL

ENV NODE_ENV=${TIMESTAMPED_FOR_F1_DASHBOARD_NODE_ENV}
ENV HOST=${TIMESTAMPED_FOR_F1_DASHBOARD_HOST}
ENV PORT=${TIMESTAMPED_FOR_F1_DASHBOARD_PORT}
ENV TIMESTAMPED_FOR_F1_DASHBOARD_WEB_API_BASE_URL=${TIMESTAMPED_FOR_F1_DASHBOARD_WEB_API_BASE_URL}

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
CMD ["node", "server.js"]
