# User config
admin_user: "{{ vault_admin_user }}"
admin_ssh_public_key: "{{ vault_admin_ssh_public_key }}"

server_user: "{{ vault_server_user }}"

# Services config
timestamped_for_f1_openf1_db_root_username: "{{ vault_timestamped_for_f1_openf1_db_root_username }}"
timestamped_for_f1_openf1_db_root_password: "{{ vault_timestamped_for_f1_openf1_db_root_password }}"
timestamped_for_f1_openf1_db_port: "{{ vault_timestamped_for_f1_openf1_db_port }}"
timestamped_for_f1_openf1_db_name: "{{ vault_timestamped_for_f1_openf1_db_name }}"

timestamped_for_f1_openf1_api_host: "{{ vault_timestamped_for_f1_openf1_api_host }}"
timestamped_for_f1_openf1_api_port: "{{ vault_timestamped_for_f1_openf1_api_port }}"

timestamped_for_f1_cache_host: "{{ vault_timestamped_for_f1_cache_host }}"
timestamped_for_f1_cache_port: "{{ vault_timestamped_for_f1_cache_port }}"
timestamped_for_f1_cache_username: "{{ vault_timestamped_for_f1_cache_username }}"
timestamped_for_f1_cache_password: "{{ vault_timestamped_for_f1_cache_password }}"
timestamped_for_f1_cache_db_name: "{{ vault_timestamped_for_f1_cache_db_name }}"

timestamped_for_f1_cache_api_host: "{{ vault_timestamped_for_f1_cache_api_host }}"
timestamped_for_f1_cache_api_port: "{{ vault_timestamped_for_f1_cache_api_port }}"

timestamped_for_f1_web_api_port: "{{ vault_timestamped_for_f1_web_api_port }}"
timestamped_for_f1_web_api_base_url: "https://timestampedforf1.jeffreyjpz.com/api/v1"

timestamped_for_f1_dashboard_node_env: "production"
timestamped_for_f1_dashboard_host: "{{ vault_timestamped_for_f1_dashboard_host }}"
timestamped_for_f1_dashboard_port: "{{ vault_timestamped_for_f1_dashboard_port }}"

timestamped_for_f1_env_vars:
  TIMESTAMPED_FOR_F1_OPENF1_DB_ROOT_USERNAME: "{{ timestamped_for_f1_openf1_db_root_username }}"
  TIMESTAMPED_FOR_F1_OPENF1_DB_ROOT_PASSWORD: "{{ timestamped_for_f1_openf1_db_root_password }}"
  TIMESTAMPED_FOR_F1_OPENF1_DB_PORT: "{{ timestamped_for_f1_openf1_db_port }}"
  TIMESTAMPED_FOR_F1_OPENF1_DB_NAME: "{{ timestamped_for_f1_openf1_db_name }}"
  TIMESTAMPED_FOR_F1_OPENF1_API_HOST: "{{ timestamped_for_f1_openf1_api_host }}"
  TIMESTAMPED_FOR_F1_OPENF1_API_PORT: "{{ timestamped_for_f1_openf1_api_port }}"
  TIMESTAMPED_FOR_F1_CACHE_HOST: "{{ timestamped_for_f1_cache_host }}"
  TIMESTAMPED_FOR_F1_CACHE_PORT: "{{ timestamped_for_f1_cache_port }}"
  TIMESTAMPED_FOR_F1_CACHE_USERNAME: "{{ timestamped_for_f1_cache_username }}"
  TIMESTAMPED_FOR_F1_CACHE_PASSWORD: "{{ timestamped_for_f1_cache_password }}"
  TIMESTAMPED_FOR_F1_CACHE_DB_NAME: "{{ timestamped_for_f1_cache_db_name }}"
  TIMESTAMPED_FOR_F1_CACHE_API_HOST: "{{ timestamped_for_f1_cache_api_host }}"
  TIMESTAMPED_FOR_F1_CACHE_API_PORT: "{{ timestamped_for_f1_cache_api_port }}"
  TIMESTAMPED_FOR_F1_WEB_API_PORT: "{{ timestamped_for_f1_web_api_port }}"
  NEXT_PUBLIC_TIMESTAMPED_FOR_F1_WEB_API_BASE_URL: "{{ timestamped_for_f1_web_api_base_url }}" # keep NEXT_PUBLIC prefix
  TIMESTAMPED_FOR_F1_DASHBOARD_NODE_ENV: "{{ timestamped_for_f1_dashboard_node_env }}"
  TIMESTAMPED_FOR_F1_DASHBOARD_HOST: "{{ timestamped_for_f1_dashboard_host }}"
  TIMESTAMPED_FOR_F1_DASHBOARD_PORT: "{{ timestamped_for_f1_dashboard_port }}"

timestamped_for_f1_host: "timestampedforf1.jeffreyjpz.com"