# User config
admin_user: "{{ vault_admin_user }}"
admin_ssh_public_key: "{{ vault_admin_ssh_public_key }}"

server_user: "{{ vault_server_user }}"

# Services config
timestamped_for_f1_openf1_db_root_username: "{{ vault_timestamped_for_f1_openf1_db_root_username }}"
timestamped_for_f1_openf1_db_root_password: "{{ vault_timestamped_for_f1_openf1_db_root_password }}"
timestamped_for_f1_openf1_db_port: "27017"
timestamped_for_f1_openf1_db_name: "{{ vault_timestamped_for_f1_openf1_db_name }}"

timestamped_for_f1_cache_host: "cache"
timestamped_for_f1_cache_port: "6379"
timestamped_for_f1_cache_username: "{{ vault_timestamped_for_f1_cache_username }}"
timestamped_for_f1_cache_password: "{{ vault_timestamped_for_f1_cache_password }}"
timestamped_for_f1_cache_db: "{{ vault_timestamped_for_f1_cache_db }}"

timestamped_for_f1_cache_api_ip: "0.0.0.0"
timestamped_for_f1_cache_api_port: "9090"

timestamped_for_f1_web_api_base_url: "https://timestampedforf1.jeffreyjpz.com/api/v1"

timestamped_for_f1_host: "timestampedforf1.jeffreyjpz.com"
